image: docker:20.10.16

services:
  - name: docker:20.10.16-dind
    alias: docker

stages:
  - build
  - push

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t $PRIVATE_ADDRESS:$CI_COMMIT_SHA .
  only:
    - main

push:
  stage: push
  script:
    - docker push $PRIVATE_ADDRESS:$CI_COMMIT_SHA
  only:
    - main
