image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - push

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t $PRIVATE_ADDRESS:$CI_COMMIT_SHA .
  only:
    - main

push:
  stage: push
  script:
    - docker push $PRIVATE_ADDRESS:$CI_COMMIT_SHA
  only:
    - main
