image: ubuntu:latest

stages: 
  - all

all-jobs:
  stage: all
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - apt update
    - apt -y install git curl
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - chmod +x get-docker.sh
    - ./get-docker.sh
    - git clone $CI_PROJECT_URL
    - cd $(echo $CI_PROJECT_NAME | cut -d'/' -f2)
    - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
    - export REPO_NAME=$(echo $CI_PROJECT_NAME | cut -d'/' -f2)
    - docker build -t $DOCKER_USERNAME/$REPO_NAME:$CI_COMMIT_TAG .
    - docker tag $DOCKER_USERNAME/$REPO_NAME:$CI_COMMIT_TAG $DOCKER_USERNAME/$REPO_NAME:latest
    - docker tag $DOCKER_USERNAME/$REPO_NAME:$CI_COMMIT_TAG $PRIVATE_ADDRESS/$REPO_NAME:$CI_COMMIT_TAG
    - docker tag $DOCKER_USERNAME/$REPO_NAME:$CI_COMMIT_TAG $PRIVATE_ADDRESS/$REPO_NAME:latest
    - docker push $DOCKER_USERNAME/$REPO_NAME:$CI_COMMIT_TAG
    - docker push $DOCKER_USERNAME/$REPO_NAME:latest
    - docker push $PRIVATE_ADDRESS/$REPO_NAME:$CI_COMMIT_TAG
    - docker push $PRIVATE_ADDRESS/$REPO_NAME:latest
    - echo "All jobs completed successfully."
