image: docker:20.10.16

services:
  - name: docker:20.10.16-dind
    alias: docker

stages:
  - build&push

before_script:
  - docker info

build&push:
  stage: build&push
  script:
    - docker build -t $PRIVATE_ADDRESS:$CI_COMMIT_SHA .
    - docker push $PRIVATE_ADDRESS:$CI_COMMIT_SHA
    - docker tag $PRIVATE_ADDRESS:$CI_COMMIT_SHA $PRIVATE_ADDRESS:latest
    - docker push $PRIVATE_ADDRESS:latest
    - docker images
  only:
    - main
