version: '3.8'
services:
  ocr:
    build:
      context: .
      dockerfile: Dockerfile
    image: paidax/ocr:0.5
    container_name: ocr
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ${PWD}:/home/ocr
    ports:
      - 9832:9832
    command: tail -f /dev/null