version: '3.8'
services:
  ocr:
    build:
      context: .
      dockerfile: Dockerfile
    image: paidax/ocr_modelscope:0.6.3
    container_name: ocr
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 9533:9533
    command: uvicorn main:app --host 0.0.0.0 --port 9533